### ISSUE TITLE
Windows: open file error

### ISSUE THREAD

**Issue by Trekky12** [authpass/authpass#154]
When opening a local file on windows the database can't be opened and the following error is shown:
![grafik](https://user-images.githubusercontent.com/3930110/93917337-2b3b5e00-fd0b-11ea-8d88-80f68b2bb93e.png)

When opening the file via webdav on windows the error is:
![grafik](https://user-images.githubusercontent.com/3930110/93917676-96853000-fd0b-11ea-8956-f4fa86d060bd.png)

**Comment by hpoul** [comment]
Hi, can you please check the app bar menu -> About - there you will find the path to the log file.
Maybe you could either share the log file with me: herbert@authpass.app - or search for those error messages and see if there is a stacktrace or other error details, maybe with some lines for context before and after.

**Comment by Trekky12** [comment]
Hey, 
unfortunately there is no log file ant there is only "No Log File?!"

**Comment by exalented** [comment]
Downgrade to build 1.7.7_1519 to temporarily fix this issue.
https://data.authpass.app/data/artifacts/AuthPass-setup-1.7.7_1519.exe

**Comment by Trekky12** [comment]
Yes I can confirm that this version is working 👍

**Comment by Turux** [comment]
I am experiencing something similar when attempting to load a file from CloudStorage (I have tried with Google Drive). I get the following error message when attempting to insert the master password:
`Unknown error while trying to open file. type 'bool' is not a subtype of type 'String' in type cast`

I have not seen the source code (my bad) but it looks like is somehow passing the master password as a bool rather than a String... 🧐

**Comment by hpoul** [comment]
@Trekky12 btw did you try to run the latest AuthPass master version in an ide on windows? I have no way to debug this

**Comment by Trekky12** [comment]
@hpoul actually the error is still in the lastest master version.

You can find the logfile here:
```
flutter: 2020-10-13 19:59:29.600996 WARNING biometric_storage_win32 - Error: 0 
### WindowsException: Error 0x00000000: Der Vorgang wurde erfolgreich beendet.
Waiting for Windows to report its views...                           3ms
Syncing files to device Windows...                              
flutter: Forking zone.

flutter: 2020-10-13 19:59:29.736476 FINE onboarding - with: 1264.0

flutter: Forking zone.

flutter: 2020-10-13 19:59:29.785989 FINE onboarding - with: 1264.0

flutter: Forking zone.

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'bool' is not a subtype of type 'String' in type cast

#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)

<asynchronous suspension>

#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)

#2      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)

#3      getTemporaryDirectory (package:path_provider/path_provider.dart:60:39)

#4      PathUtils.getTemporaryDirectory (package:authpass/utils/path_utils.dart:31:13)

#5      PathUtils.getLogDirectory (package:authpass/utils/path_utils.dart:77:38)

#6      LoggingUtils._rotatingFileLogger.<anonymous closure> (package:authpass/utils/logging_utils.dart:24:43)

<asynchronous suspension>

#7      LoggingUtils._rotatingFileLogger.<anonymous closure> (package:authpass/utils/logging_utils.dart)

#8      new AsyncInitializingLogHandler (package:logging_appenders/src/rotating_file_appender.dart:179:12)

#9      LoggingUtils._rotatingFileLogger (package:authpass/utils/logging_utils.dart:22:11)

#10     LoggingUtils.setupLogging (package:authpass/utils/logging_utils.dart:44:7)

#11     initIsolate (package:authpass/main.dart:50:18)

#12     startApp (package:authpass/main.dart:69:3)

#13     EnvAppBase.start (package:authpass/env/env.dart:45:11)

#14     main (package:authpass/env/development.dart:4:50)

#15     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)

#16     _rootRun (dart:async/zone.dart:1190:13)

#17     _CustomZone.run (dart:async/zone.dart:1093:19)

#18     _runZoned (dart:async/zone.dart:1630:10)

#19     runZonedGuarded (dart:async/zone.dart:1618:12)

#20     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)

#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)

#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


Syncing files to device Windows...                                 344ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:64391/fFxgkNX_4tc=/
flutter: 2020-10-13 19:59:31.138193 FINEST main - didPush
flutter: 2020-10-13 19:59:31.138193 FINER analytics - (noop) screen(/createFile)
flutter: 2020-10-13 19:59:31.145146 FINER analytics - (noop) event(onboarding, click, label=onboardingNewbie, null) - parameters: {}
flutter: Forking zone.
flutter: Forking zone.
flutter: Forking zone.
flutter: 2020-10-13 19:59:34.209637 FINER future_task_state_mixin - Running task null
flutter: 2020-10-13 19:59:34.215616 FINER analytics - (noop) event(track, createFile, , null) - parameters: {}
flutter: 2020-10-13 19:59:34.273436 INFO future_task_state_mixin - Initialized task with null
flutter: 2020-10-13 19:59:34.274465 INFO main - KdbxBloc updated.
flutter: 2020-10-13 19:59:34.305379 SEVERE create_file - Error while creating file.
### _CastError: type 'bool' is not a subtype of type 'String' in type cast
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
#3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:109:39)
#4      PathUtils.getAppDocDirectory (package:authpass/utils/path_utils.dart:40:23)
#5      KdbxBloc._localFileSourceForDbName (package:authpass/bloc/kdbx_bloc.dart:570:38)
#6      KdbxBloc.createFile (package:authpass/bloc/kdbx_bloc.dart:559:31)
#7      _CreateFileState._submitCallback.<anonymous closure> (package:authpass/ui/screens/create_file.dart:144:44)
#8      FutureTaskStateMixin.asyncRunTask (package:flutter_async_utils/src/future_task_state_mixin.dart:134:30)
#9      FutureTaskStateMixin.asyncTaskCallback.<anonymous closure> (package:flutter_async_utils/src/future_task_state_mixin.dart:113:7)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:985:20)
#11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:368:19)
#23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:348:22)
#24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:268:11)
#25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:303:7)
#26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:267:5)
#27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:225:7)
#28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:208:7)
#29     _rootRunUnary (dart:async/zone.dart:1206:13)
#30     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#32     _invoke1 (dart:ui/hooks.dart:265:10)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

flutter: 2020-10-13 19:59:34.310812 FINEST main - didPush
flutter: 2020-10-13 19:59:34.310812 FINER analytics - (noop) screen(/dialog/alert/error)
flutter: 2020-10-13 19:59:34.312771 FINE future_task_state_mixin - Task null completed. 0 queued tasks remaining.
flutter: 2020-10-13 19:59:34.312771 SHOUT main - Unhandled error in app.
### _CastError: type 'bool' is not a subtype of type 'String' in type cast
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
#3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:109:39)
#4      PathUtils.getAppDocDirectory (package:authpass/utils/path_utils.dart:40:23)
#5      KdbxBloc._localFileSourceForDbName (package:authpass/bloc/kdbx_bloc.dart:570:38)
#6      KdbxBloc.createFile (package:authpass/bloc/kdbx_bloc.dart:559:31)
#7      _CreateFileState._submitCallback.<anonymous closure> (package:authpass/ui/screens/create_file.dart:144:44)
#8      FutureTaskStateMixin.asyncRunTask (package:flutter_async_utils/src/future_task_state_mixin.dart:134:30)
#9      FutureTaskStateMixin.asyncTaskCallback.<anonymous closure> (package:flutter_async_utils/src/future_task_state_mixin.dart:113:7)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:985:20)
#11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:368:19)
#23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:348:22)
#24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:268:11)
#25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:303:7)
#26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:267:5)
#27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:225:7)
#28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:208:7)
#29     _rootRunUnary (dart:async/zone.dart:1206:13)
#30     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#32     _invoke1 (dart:ui/hooks.dart:265:10)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

flutter: 2020-10-13 19:59:34.314794 FINEST main - didPush
flutter: 2020-10-13 19:59:34.314794 FINER analytics - (noop) screen(/dialog/alert/error)
flutter: 2020-10-13 19:59:34.317787 SHOUT main - Unhandled error in app.
### _CastError: type 'bool' is not a subtype of type 'String' in type cast
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
#3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:109:39)
#4      PathUtils.getAppDocDirectory (package:authpass/utils/path_utils.dart:40:23)
#5      KdbxBloc._localFileSourceForDbName (package:authpass/bloc/kdbx_bloc.dart:570:38)
#6      KdbxBloc.createFile (package:authpass/bloc/kdbx_bloc.dart:559:31)
#7      _CreateFileState._submitCallback.<anonymous closure> (package:authpass/ui/screens/create_file.dart:144:44)
#8      FutureTaskStateMixin.asyncRunTask (package:flutter_async_utils/src/future_task_state_mixin.dart:134:30)
#9      FutureTaskStateMixin.asyncTaskCallback.<anonymous closure> (package:flutter_async_utils/src/future_task_state_mixin.dart:113:7)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:985:20)
#11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:368:19)
#23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:348:22)
#24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:268:11)
#25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:303:7)
#26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:267:5)
#27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:225:7)
#28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:208:7)
#29     _rootRunUnary (dart:async/zone.dart:1206:13)
#30     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#32     _invoke1 (dart:ui/hooks.dart:265:10)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

**Comment by Trekky12** [comment]
Unfortunately I tested the version before your last commit, sorry! I will try to test the lastest version in the next days 👍

**Comment by hpoul** [comment]
I think we'll merge this together with #178 - to avoid duplicating things i'm closing this, let's continue the discussion in #178
