### ISSUE TITLE
Android: Correctly handle non-persistable file permissions

### ISSUE THREAD

**Issue by hpoul** [authpass/authpass#171]
When a user opens a `kdbx` file from an external application with AuthPass, sometimes those apps do not provide persistable permissions (e.g. using the synology app or the nextcloud app(?) - i've also seen errors reported from `com.mixplorer.silver.fileProvider `).

The `FilePickerWritable` should already tell us whether we have "persistable" permissions to a file. We should correctly handle this, and not offer a 'Save password` during unlock, and make sure the 'recently opened files' give an appropriate error message.

**Comment by TomerPacific** [comment]
@hpoul , I'd like to help out. I will appreciate it if you can elaborate more on what solution is necessary and what you are expecting.

**Comment by hpoul** [comment]
@TomerPacific cool, would be awesome. Sure, are you an android user / do you have experience with android development? (I think on iOS the same problem would exist) - but basically if you open a `.kdbx` file from an external file manager.. (maybe try the mentioned `com.mixplorer.silver.fileProvider`) sometimes AuthPass only gets one-time file handles from which to read in the current session, but not after shutting down and restarting. Ie. the next time you open AuthPass you would have the `kdbx` file in the list of 'recents', but when you click on it you would see an error message about not being able to open the file (or a file not found error). You could first try to reproduce the problem..

In theory - I haven't really tried it yet, the `FilePickerWritable` plugin should already provide a `persistable` property: https://pub.dev/documentation/file_picker_writable/latest/file_picker_writable/FileInfo/persistable.html and I would hope that this is `false` if its a transient content url. If this is true, it would just be a matter of checking for this property, and not persisting the opened file in the `recents`.
On the other hand if this can't be detected easily, it would also be enough to gracefully handle that error.

<details>
<summary>Here is an example exception</summary>

```
2020-10-02 12:29:01.851918 SHOUT main - Unhandled error in app.
### PlatformException: PlatformException(FilePickerError, d.a.a.a.b: Unable to load file info from content://com.mixplorer.silver.fileProvider/CEWvRkIDpqtERwAof2I_VEIdvmHIRciECcsL_P8=/Keepass.kdbx, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:571)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359)
<asynchronous suspension>
#3      FilePickerWritable.readFile (package:file_picker_writable/src/file_picker_writable.dart:254)
<asynchronous suspension>
#4      FileSourceLocal._accessFile (package:authpass/bloc/kdbx/file_source_local.dart:80)
<asynchronous suspension>
#5      FileSourceLocal.load (package:authpass/bloc/kdbx/file_source_local.dart:72)
<asynchronous suspension>
#6      FileSource.content (package:authpass/bloc/kdbx/file_source.dart:83)
<asynchronous suspension>
#7      Stream.last.<anonymous closure> (dart:async/stream.dart)
<asynchronous suspension>

2020-10-02 12:29:01.852117 FINEST main - didPush
2020-10-02 12:29:01.852177 FINER analytics - (noop) screen(/dialog/alert/error)
2020-10-02 12:29:01.852351 FINE file_picker_writable - Native Log: debug: main Error while handling method call i.b.b.a.i@8cd7c82  Exception: Unable to load file info from content://com.mixplorer.silver.fileProvider/CEWvRkIDpqtERwAof2I_VEIdvmHIRciECcsL_P8=/Keepass.kdbx
d.a.a.a.b: Unable to load file info from content://com.mixplorer.silver.fileProvider/CEWvRkIDpqtERwAof2I_VEIdvmHIRciECcsL_P8=/Keepass.kdbx
	at d.a.a.a.c$g.i(Unknown Source:133)
	at d.a.a.a.c$g.e(Unknown Source:10)
	at kotlinx.coroutines.y1.b.b(Unknown Source:9)
	at kotlinx.coroutines.d.c(Unknown Source:55)
	at kotlinx.coroutines.c.c(Unknown Source:0)
	at d.a.a.a.c.q(Unknown Source:10)
	at d.a.a.a.c$b.i(Unknown Source:92)
	at j.d0.j.a.a.j(Unknown Source:8)
	at kotlinx.coroutines.k0.run(Unknown Source:93)
	at kotlinx.coroutines.z1.b.v(Unknown Source:0)
	at kotlinx.coroutines.z1.b$a.c(Unknown Source:14)
	at kotlinx.coroutines.z1.b$a.m(Unknown Source:28)
	at kotlinx.coroutines.z1.b$a.run(Unknown Source:0)

```

</details>

does this make sense to you?

**Comment by TomerPacific** [comment]
@hpoul , thanks for the quick reply and the thorough explanation. My background is being a Mobile developer, but I am not that fluent in Flutter. I want to verify that I understand the steps to reproduce this issue correctly:

1. Download AuthPass to an Android device
2. Create a .kdbx file
2.  Use the  com.mixplorer.silver.fileProvider application to open it
3.  Shut down/restart device (or AuthPass)
4.  Click on the .kdbx file that was created to try and open it

**Comment by hpoul** [comment]
@TomerPacific exactly.. ad 4) just restarting AuthPass is enough (swiping it away from the recents, or just tapping 'back' until it closes), ad 5) yep, selecting the .kdbx file from the "recents" within authpass.

(I haven't used that file manager myself yet though.. sometimes, it's possible that there are two modes like 'Open with xxx' and 'Export to ...' - and one would offer persistable permission, while the other only temporary.. if you can't reproduce it let me know and i'll take a closer look)

**Comment by TomerPacific** [comment]
@hpoul , it has taken me some time to set up my development environment. Trying to recreate the issue, I see that the application you want to open the kdbx file with costs money.

https://play.google.com/store/apps/details?id=com.mixplorer.silver&hl=en&gl=US

Is this the right application?

**Comment by hpoul** [comment]
@TomerPacific um.. i've never tried it, just had the ID from a user report.. although since it was an f-droid user I would *highly* doubt that he paid for the app.. anyhooo.. you can also try other apps.. for example i've used the samsung "internet" browser to download https://github.com/authpass/authpass/blob/master/_docs/screenshot_example.kdbx and then opened it with authpass.. then killed authpass.. and upon restart selected the file and got that error:

![2020-10-12](https://user-images.githubusercontent.com/313066/95789034-0d936000-0cdd-11eb-8c21-418821cbb3c1.jpg)

unfortunately for example google chrome correctly gave persistable permissions.. so not all apps have this problems.. if you don't have a samsung phone (with samsung internet app) you could try other file managers (or browsers, like firefox?).. or.. you could also create a simple dummy android app which simply launches a new 'open file' intent with some kdbx file 😅️

**Comment by TomerPacific** [comment]
@hpoul , sorry for responding after a while. I am having a hard time recreating the crash.
I am looking into areas in the code where the crash might happen from so I can understand where it is needed to make amendments.

**Comment by hpoul** [comment]
@TomerPacific I can easily reproduce this with firefox.. here is a screecast: https://youtu.be/qf8bCL2glIY sorry for it being sooooo sloooowww.. it seems my old phone plus screenrecording is grippling slow.. let me know if this clears things up.. simply try to download the kdbx file with firefox, open it directly from firefox with AuthPass. . once it is open, just kill AuthPass (swipe away from `recents`) .. and then relaunch AuthPass.. if you then select it from the 'recents' it will show this error.

**Comment by TomerPacific** [comment]
@hpoul - sorry for not being more active, but I am not getting to handling this issue. If you prefer, you can let someone else take it as I do not know when I will have enough time to handle it properly.

**Comment by hpoul** [comment]
@TomerPacific no worries. did you watch my video which shows the exact steps to reproduce this error? Have you tried it with firefox and still couldn't get an error message?

**Comment by TomerPacific** [comment]
@hpoul - I have seen the video and tried to reproduce on an emulated device, but had a hard time with it. Will find time to reproduce it on a physical device.
