### ISSUE TITLE
Authentication error on android when using biometrics

### ISSUE THREAD

**Issue by teemue** [authpass/authpass#193]
**Describe the bug**
When trying to open a database file with biometric option checked, right after reading fingerprint AuthPass throws an error saying
Unable to open file
Unknown error while trying to open file. AuthException{code: AuthExceptionCode.unknown
message: Unexpexted authentication error. the master key android-keystore://QuickUnlock_master_key exists
but is unusable)

The database opens with password.

**To Reproduce**
1. Open database
2. Check 'Save Password with biometric key store?"
3. Click 'Continue'
4. Read fingerprint

**Expected behavior**
Successfully opened database

**Smartphone (please complete the following information):**
 - Device: Nokia 5.1
 - OS: Android  10
 - AuthPass Version 1.7.10+149

**Additional context**
I tried removing and readding fingerprints to the phone's settings - no success

**Comment by hpoul** [comment]
is it possible that you had an earlier version of AuthPass installed previously, uninstalled it, and later installed this newer version?

**Comment by teemue** [comment]
I did, like months ago

**Comment by hpoul** [comment]
@teemue i recently discovered a bug that the old encryption keys were stored in the android backup - after uninstall/install those were restored, but no longer readable (since they are encrypted by a device provided key). Since this version the backup is disabled completely. So could you try to remove the app again and reinstall it? I hope this also clears the backup.

**Comment by teemue** [comment]
I cleared data and cache of authpass and then  removed it and reinstalled (via f-droid as before), it still gives the same error.

**Comment by hpoul** [comment]
can you please share your log file? (overflow menu -> 'Email Support'), this will bring up an email composer with the log file attached, you can just send it to the support address (or to yourself if you want to inspect the contents first) - thanks

**Comment by teemue** [comment]
Sure! Just did

**Comment by hpoul** [comment]
thanks - btw. did you also try to delete data *after* the installation, or only before uninstall 😅️

**Comment by teemue** [comment]
Both,actually:)

**Comment by hpoul** [comment]
this is very weird.. and i also missed the root cause 

```
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1348)
	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1413)
```

the funny thing is, I've just got the same error in an emulator. But the fix was to add a new fingerprint into the settings, which immediately solved the issue 🤔️ I'm a bit bummed that you already tried this.. 

could you maybe try out another build, either play store or https://data.authpass.app/data/artifacts/authpass-sideload-1.7.10_1614.apk .. they basically only differ in package name, and would at least make sure it has nothing to do with leftovers from previous installs.

**Comment by teemue** [comment]
Not working. Steps I proceeded:

1. Remove data & cache
2. Remove previous AuthPass installation
3. Install AuthPass from the app link you provided
4. Open database -> the same error
5. Remove and add fingerprints again
4. Open database -> the same error

I tried creating a new database with AuthPass but no luck.

[app.log.txt](https://github.com/authpass/authpass/files/5434384/app.log.txt)
