### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: certificate has expired

### ISSUE THREAD

**Issue by Zebartin** [authpass/authpass#275]
**Describe the bug**
Can not open kdbx file with an error report reading certificate has expired.
I have no problem with accessing from my Android phone at the same time.

**To Reproduce**
Just opened my last opened kdbx file and failed to access it.
I came across similar issue when I tried to log in the authpass cloud.

**Expected behavior**
My file should be opened and the authpass cloud can be logged in as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/16185081/135702303-2a203c5e-98ee-43cf-93be-9174f18035bb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.9.4+1872

**Smartphone (please complete the following information):**
 - Device: Huawei Honor V30
 - OS: Harmony
 - Version 1.9.4+1872

**Additional context**
The most significiant network change recently that occurs to me is that the WiFi in my room was reset.

**Comment by hpoul** [comment]
Can you access https://cloud.authpass.app/ in your browser? (A "not found" is okay, as long as the ssl connection can be authenticated)?

Can you make sure the date/time of you PC is set correctly? 😬

**Comment by Zebartin** [comment]
> Can you access https://cloud.authpass.app/ in your browser? (A "not found" is okay, as long as the ssl connection can be authenticated)?
> 
> Can you make sure the date/time of you PC is set correctly? 😬

Yes for both. I can access it on my Chrome and the date&time on my PC is setup as synchronized with the Internet.

**Comment by hpoul** [comment]
Can you please check and maybe attach the log file? You can find the path in the about dialog.

**Comment by Zebartin** [comment]
> Can you please check and maybe attach the log file? You can find the path in the about dialog.

Here it is, when I was trying to logging in to the cloud. Please take a look.
```
2021-10-02 15:01:15.489101 FINER future_task_state_mixin - Running task null
2021-10-02 15:01:15.489101 INFO future_task_state_mixin - Initialized task with null
2021-10-02 15:01:15.489101 FINER analytics - (ga) event(authSend, authSend, label=auth, null) - parameters: {}
2021-10-02 15:01:15.489101 FINEST openapi_client_base - Expanded Uri for request to https://cloud.authpass.app/user/register  (baseUri: https://cloud.authpass.app/)
2021-10-02 15:01:16.290096 FINEST main - didPush
2021-10-02 15:01:16.290096 FINER analytics - (ga) screen(/dialog/alert/error)
2021-10-02 15:01:16.290096 FINE future_task_state_mixin - Task null completed. 0 queued tasks remaining.
2021-10-02 15:01:16.290360 SHOUT main - Unhandled error in app.
### HandshakeException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: certificate has expired(../../third_party/boringssl/src/ssl/handshake.cc:359))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:101)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:794)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:924)
<asynchronous suspension>
```

**Comment by Zebartin** [comment]
What can I do now to temporarily resolve the error? I have tried reinstalling and it went the same.
