### ISSUE TITLE
1.9.5 Errors when opening "Preferences" and "Send logs"

### ISSUE THREAD

**Issue by MkQtS** [authpass/authpass#306]
**Describe the bug**

I am using authpass-sideload-1.9.5. The application reports errors when opening *Preferences* or *Send logs*.

**To Reproduce**

1. Just open *Preferences* or *Send logs* from home page
2. See error

**Screenshots**

![Preferences](https://user-images.githubusercontent.com/81752398/173236840-667431f9-f2a9-4854-83e1-a10adaf76469.png)
![Send logs](https://user-images.githubusercontent.com/81752398/173236845-6ae67b7c-829f-4353-92af-8382bc68ca85.png)

**Smartphone (please complete the following information):**

 - Device: Redmi K30 Pro
 - OS: MIUI 13, Android 12
 - Version: authpass-sideload-1.9.5.

**Comment by MkQtS** [comment]
The log is as follows:

```
2022-06-12 21:48:32.832101 INFO logging_utils - Running in isolate main (538598059) main (538598059)
2022-06-12 21:48:32.832463 INFO main - Initialized logger. (android, SKQ1.211006.001 test-keys) 0
2022-06-12 21:48:32.832641 FINEST platform - error fetching info. 
2022-06-12 21:48:32.832721 INFO main - {script: /main.dart, executable: throws: type 'Null' is not a subtype of type 'String', resolvedExecutable: /system/bin/app_process64, executableArguments: []}
2022-06-12 21:48:32.833124 FINE simple_json_persistence - Deserializing AppData
2022-06-12 21:48:32.835374 FINE persistence_io - Writing into File: '/data/user/0/design.codeux.authpass.sideload/app_flutter/AppData.json'
2022-06-12 21:48:32.837829 FINEST simple_json_persistence - AppData updating value.
2022-06-12 21:48:32.838076 FINE main - Building AuthPass App state. route: /
2022-06-12 21:48:32.838228 INFO theme - using default theme TargetPlatform.android -- SKQ1.211006.001 test-keys
2022-06-12 21:48:32.838320 FINE main - appData.themeFontSizeFactor: null
2022-06-12 21:48:32.838344 INFO theme - using default theme TargetPlatform.android -- SKQ1.211006.001 test-keys
2022-06-12 21:48:32.838378 FINE main - appData.themeFontSizeFactor: null
2022-06-12 21:48:32.838654 INFO main - creating AuthPassCloudBloc.
2022-06-12 21:48:32.838699 FINE authpass_cloud_bloc - Creating AuthPassCloudBloc with FeatureFlags {
  authpassCloud=true,
  authpassCloudUri=https://cloud.authpass.app/,
}
2022-06-12 21:48:32.838725 FINEST authpass_cloud_bloc - Loading token.
2022-06-12 21:48:32.838866 INFO authpass_cloud_provider - Setting AuthPassCloudBloc to Instance of 'AuthPassCloudBloc'
2022-06-12 21:48:32.841508 FINER format_utils - Initialized with locale en
2022-06-12 21:48:32.841716 FINE main - initialRoute: /
2022-06-12 21:48:32.841845 FINEST main - didPush
2022-06-12 21:48:32.843982 FINE onboarding - height: 0.0
2022-06-12 21:48:32.844292 FINE onboarding - with: 0.0
2022-06-12 21:48:32.844574 FINE onboarding - with: 0.0
2022-06-12 21:48:32.852561 FINE logging_utils - Logging into LocalFile: '/data/user/0/design.codeux.authpass.sideload/cache/logs/app.log.txt'
2022-06-12 21:48:32.853654 FINER format_utils - Initialized with locale en
2022-06-12 21:48:32.853979 FINE onboarding - height: 872.7272727272727
2022-06-12 21:48:32.854114 FINE onboarding - with: 392.72727272727275
2022-06-12 21:48:32.854357 FINE onboarding - with: 392.72727272727275
2022-06-12 21:48:32.856396 FINEST biometric_storage - getting storage. was created: true
2022-06-12 21:48:32.862443 FINE file_picker_writable - Native Log: debug: main onNewIntent(null) 
2022-06-12 21:48:32.862611 FINE file_picker_writable - Native Log: debug: main Got method call: init 
2022-06-12 21:48:32.872019 FINE analytics - Got PackageInfo: AuthPass SL, 1896, design.codeux.authpass.sideload - UserAgent: Mozilla/5.0 (Linux; Android 12; Redmi K30 Pro; zh-cn) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36
2022-06-12 21:48:32.872669 FINER analytics - (ga) screen(/)
2022-06-12 21:48:32.872783 FINEST analytics - (ga) timing(startup, 9, category: startup, label: startup firstRun)
2022-06-12 21:48:32.872871 FINER analytics - (ga) screen(/onboarding)
2022-06-12 21:48:32.872904 FINEST analytics - (ga) Registering analytics tracker. 80d6ee44-9dc1-4606-9136-51447df3d7aa
2022-06-12 21:48:32.873018 FINER analytics - (ga) event(track, launch, , null) - parameters: {cd4: light}
2022-06-12 21:48:32.937434 FINER analytics - (ga) event(track, init, , 0) - parameters: {cd2: null, cd3: Redmi K30 Pro}
2022-06-12 21:48:33.769176 FINEST main - didPush
2022-06-12 21:48:33.769656 FINER analytics - (ga) screen(/selectFile)
2022-06-12 21:48:33.770035 FINER analytics - (ga) event(click, click, label=onboardingExisting, null) - parameters: {}
2022-06-12 21:48:33.772005 FINER authpass.select_file_screen - didChangeDependencies false
2022-06-12 21:48:33.777446 FINER future_task_state_mixin - Running task Quick unlocking files …
2022-06-12 21:48:33.777523 INFO future_task_state_mixin - Initialized task with Quick unlocking files …
2022-06-12 21:48:33.777589 FINE future_task_state_mixin - Progress Label changed to Quick unlocking files … (hasListeners: true)
2022-06-12 21:48:33.777644 FINE future_task_state_mixin - proxy: label changed to Quick unlocking files … (Instance of 'FutureTask')
2022-06-12 21:48:33.777797 FINER authpass.select_file_screen - opening quick unlock. 1 true true
2022-06-12 21:48:33.777843 FINER kdbx_bloc - Checking quick unlock.
2022-06-12 21:48:33.778038 INFO main - KdbxBloc updated.
2022-06-12 21:48:33.780903 FINER kdbx_bloc - supportBiometricKeyStore: CanAuthenticateResponse.success
2022-06-12 21:48:33.781278 FINEST biometric_storage - getting storage. was created: true
2022-06-12 21:48:33.781543 FINER kdbx_bloc - No quick unlock available.
2022-06-12 21:48:33.781716 FINER analytics - (ga) event(track, quickUnlock, , 0) - parameters: {}
2022-06-12 21:48:33.781773 INFO authpass.select_file_screen - opened 0 files with quick unlock. false
2022-06-12 21:48:33.781813 FINE future_task_state_mixin - Task Quick unlocking files … completed. 0 queued tasks remaining.
2022-06-12 21:48:34.344344 FINEST main - didPush
2022-06-12 21:48:34.344689 FINER analytics - (ga) screen(_PopupMenuRoute<(() => void)?>)
2022-06-12 21:48:35.837979 FINER analytics - (ga) screen(/selectFile)
2022-06-12 21:48:35.838927 FINER analytics - (ga) event(preferences, preferences, , null) - parameters: {}
2022-06-12 21:48:35.839182 FINEST main - didPush
2022-06-12 21:48:35.839462 FINER analytics - (ga) screen(/preferences)
2022-06-12 21:48:35.854955 SHOUT main - Unhandled error in app.
### PlatformException: PlatformException(error, Unsupported value: '{"enableDebug":false}' of type 'class org.json.JSONObject', null, java.lang.IllegalArgumentException: Unsupported value: '{"enableDebug":false}' of type 'class org.json.JSONObject'
	at c6.q.p(Unknown Source:444)
	at c6.r.a(Unknown Source:11)
	at c6.k$a$a.a(Unknown Source:10)
	at h5.k.C(Unknown Source:116)
	at c6.k$a.a(Unknown Source:17)
	at q5.c.l(Unknown Source:18)
	at q5.c.m(Unknown Source:20)
	at q5.c.i(Unknown Source:0)
	at q5.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367)
<asynchronous suspension>
#3      AutofillService.getPreferences (package:autofill_service/autofill_service.dart:98)
<asynchronous suspension>
#4      _PreferencesBodyState._doInit (package:authpass/ui/screens/preferences.dart:82)
<asynchronous suspension>

2022-06-12 21:48:35.855614 FINEST main - didPush
2022-06-12 21:48:35.855815 FINER analytics - (ga) screen(/dialog/alert/error)
2022-06-12 21:48:38.680269 FINER analytics - (ga) screen(/preferences)
2022-06-12 21:48:39.823130 FINER analytics - (ga) screen(/selectFile)
2022-06-12 21:48:40.389622 FINEST main - didPush
2022-06-12 21:48:40.390386 FINER analytics - (ga) screen(_PopupMenuRoute<(() => void)?>)
2022-06-12 21:48:41.634664 FINER analytics - (ga) screen(/selectFile)
2022-06-12 21:48:41.635313 FINER analytics - (ga) event(emailSupport, emailSupport, , null) - parameters: {}
2022-06-12 21:48:41.639564 SHOUT main - Unhandled error in app.
### PlatformException: PlatformException(not_available, No email clients found!, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
<asynchronous suspension>
#2      DialogUtils.sendLogs (package:authpass/utils/dialog_utils.dart:163)
<asynchronous suspension>

2022-06-12 21:48:41.640066 FINEST main - didPush
2022-06-12 21:48:41.640273 FINER analytics - (ga) screen(/dialog/alert/error)
2022-06-12 21:48:42.837272 INFO main - DeviceInfo: {id: SKQ1.211006.001, tags: release-keys, type: user, model: Redmi K30 Pro, board: lmi, brand: Redmi, device: lmi, product: lmi, display: SKQ1.211006.001 test-keys, hardware: qcom, version: {baseOS: , sdkInt: 31, release: 12, codename: REL, incremental: V13.0.3.1.37.DEV, previewSdkInt: 0, securityPatch: 2022-06-01}, manufacturer: Xiaomi, isPhysicalDevice: true}
2022-06-12 21:48:45.582662 FINER analytics - (ga) screen(/selectFile)
```

**Comment by Waqar144** [comment]
Seeing this issue in 1.9.7
