### ISSUE TITLE
Debian repo version: unable to add WebDAV source

### ISSUE THREAD

**Issue by iacchi** [authpass/authpass#351]
**Describe the bug**
I'm running AuthPass from the Debian repository (just installed on a new computer) and I'm trying to access a key file on my personal webdav server. I enter all information correctly but when I click ok to load it I receive an error. Log of the error from the console below.

**To Reproduce**
1. Install AuthPass on linux from the Debian repository
2. Add WebDAV storage
3. Enter valid WebDAV credentials

**Expected behavior**
Key files are loaded from the WebDAV source

**Console error log**
flutter: 2023-09-20 12:16:00.772983 SEVERE cloud_storage_ui_auth - Error while authenticating.
### _TypeError: Null check operator used on a null value
#0      WebDavProvider.propFind.<anonymous closure> (package:authpass/cloud_storage/webdav/webdav_provider.dart:189)
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:393)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:440)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#5      new List.of (dart:core-patch/array_patch.dart:47)
#6      SetBase.toList (dart:collection/set.dart:119)
#7      WebDavProvider.propFind (package:authpass/cloud_storage/webdav/webdav_provider.dart:197)
<asynchronous suspension>
#8      WebDavProvider.clientFromAuthenticationFlow (package:authpass/cloud_storage/webdav/webdav_provider.dart:78)
<asynchronous suspension>
#9      CloudStorageProviderClientBase.startAuth (package:authpass/cloud_storage/cloud_storage_provider.dart:319)
<asynchronous suspension>
#10     CloudStorageAuthentication._startLoginFlow (package:authpass/cloud_storage/cloud_storage_ui_auth.dart:87)
<asynchronous suspension>
#11     CloudStorageAuthentication.build.<anonymous closure> (package:authpass/cloud_storage/cloud_storage_ui_auth.dart:39)
<asynchronous suspension>

**Desktop (please complete the following information):**
 - OS: Debian Unstable

**Additional context**
Full log since opening authpass here (sorry some of it is in Italian): https://pastebin.com/Zg07SV8v

**Comment by robertoszek** [comment]
Actually, I'm getting the same `Null check operator used on a null value` error on the Android app too.

Seems to be an issue introduced on the more recent versions.
After rolling back to `1.9.7+162` (via F-Droid) on Android it let me authenticate with the WebDAV source with no issues.
In Linux `1.9.7+1940` (via Flatpak) is also able to authenticate with the WebDAV source for me.

Not sure which version or commit introduced the regression but rolling back to 1.9.7 in the meantime may worth a shot.

**Comment by iacchi** [comment]
I can confirm that version 1.9.7+1941 taken from the debian repo (so installed via deb file) works. It must indeed be a general regression with version 1.9.9.

**Comment by erikvanoosten** [comment]
Same issue with version 1.9.9 on iphone.

**Comment by erikvanoosten** [comment]
The only change in `authpass/lib/cloud_storage/webdav/webdav_provider.dart` since the previous version is [this commit](https://github.com/authpass/authpass/commit/4734d8fa9cd2daf36f248e70c3dec821440d20f9). Most probably reverting this commit will fix the issue.

**Comment by dpolyakov** [comment]
same error on ios17

**Comment by Osika91** [comment]
I'm on 1.9.9+1975 version and I can't connect to the WebDAV services.

**Comment by hpoul** [comment]
@Osika91 imho this should be fixed. maybe you can try the latest beta: https://authpass.app/docs/help-us-beta-testing/#installation

**Comment by iacchi** [comment]
I can confirm that with the build for Debian dated 27 Jan 2024 I can open my WebDAV source again. I'll test on Android asap but I guess it the bug was common to all platforms it makes sense that it's fixed on all of them.

**Comment by Osika91** [comment]
> @Osika91 imho this should be fixed. maybe you can try the latest beta: https://authpass.app/docs/help-us-beta-testing/#installation

Thanks you for your feedback. I will try to use the link you give me for the latest beta !
